---
version: '3'

services:
  mysql:
    image: mariadb:latest
    container_name: drupal-mysql
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: 'yes'
      MARIADB_DATABASE: drupal
      MARIADB_USER: drupal
      MARIADB_PASSWORD: drupal
    ports:
      - 1011:3306

  redis:
    image: redis:latest
    ports:
      - 1012:6379
  drupal:
    image: drupal:8-apache
    container_name: drupal
    depends_on:
      - mysql
    restart: unless-stopped
    ports:
      - 1010:80
    volumes:
      - ./sites:/tmp/sites
      - ./phpredis:/tmp/phpredis
      - ./php_file:/tmp/phpfiles
    #command: [sh, -c, "sleep 180"]
    #command: [sh, -c, "cd /opt/drupal/web/modules/phpredis && phpize && ./configure && make && make install"]
    links:
      - redis
      - mysql
